import Head from 'next/head'
import HomeBar from '@/components/home_bar'
import Tarjeta from '@/components/tarjeta_preview'
import styles from '@/styles/Home.module.css'
import obtener from './api/firebase/get-data'
import { useEffect, useState } from 'react'

const mockInfo = [
  {
    id: "ascansjñasljcnas",
    titulo: "Num 1",
    contenido: "Quiero revisar si esto es un contenido valido",
    fecha: "24/08/2023"
  },
  {
    id: "adcajsnjasc",
    titulo: "Num 2",
    contenido: "Quiero revisar si esto es un contenido valido",
    fecha: "24/08/2023"
  }
]

export default function Home() {
  const [articulos, setArticulos] = useState([])
  const fetchData = async () => {
    try {
      const result = await obtener("articulos");
      setArticulos(result);
    } catch (error) {
      // Handle the error if needed
      console.error("Error fetching data:", error);
    }
  };
  useEffect(() => {
    fetchData()
  }, [])
  useEffect(() => {
    console.log(articulos)
  }, [articulos])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeBar enlace="/"></HomeBar>
      <div className="superCentrar">
        <div className={styles.tarjetas}>
          {articulos.map((item) => (
            <Tarjeta key={item.id} data={item} fecha={item.fecha}></Tarjeta>
          ))}
        </div>
      </div>
    </>
  )
}
